## NumPy

### 1. Basics of NumPy:

##### - Create Arrays:
- Create a 1D array of integers.
- Create a 2D array with random floats.
- Create an array of zeros and ones with a specified shape.
##### - Array Operations:
- Perform basic operations like addition, subtraction, multiplication, and division on arrays.
- Reshape an array and understand how the reshape function works.

### 2. Indexing and Slicing:
- Access specific elements of an array using indexing.
- Use slicing to extract specific portions of an array.

### 3. Mathematical Operations:
- Calculate the mean, median, and standard deviation of an array.
- Apply trigonometric and exponential functions to an array.

### 4. Linear Algebra:
- Multiply two matrices using np.dot.
- Calculate the determinant and inverse of a matrix.

### 5. Statistics:
- Generate a random dataset and calculate basic statistics.
- Use NumPy's statistical functions like np.percentile and np.histogram.

### 6. Random:
- Create a random matrix and then sort it.
- Shuffle the elements of an array.

In [130]:
# imports
import numpy as np


In [131]:
# create arrays
oned_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.random.standard_normal(size=(2,4))
zeros = np.zeros(10)
ones = np.ones(10)

In [132]:
#array operations
other_1darr = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
summed = oned_arr + other_1darr
diff = oned_arr - other_1darr
mult = oned_arr * other_1darr
div = oned_arr / other_1darr

In [133]:
# indexing and slicing
data2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr2 = np.array(data2)
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [134]:
last_vals = arr2[0:, 2]
arr2[0:, 2] = 222
arr2

array([[  1,   2, 222],
       [  4,   5, 222],
       [  7,   8, 222]])

In [135]:
# for fun: make an X with 3x3 matrix
result = np.where(np.arange(arr2.shape[1]) % 2 == 0, 0, arr2)
result[1,1] = 0
result

array([[0, 2, 0],
       [0, 0, 0],
       [0, 8, 0]])

In [136]:
arr2[:,2] = 2
arr2

array([[1, 2, 2],
       [4, 5, 2],
       [7, 8, 2]])

In [137]:
(arr2[1]).sum()

11

In [138]:
np.mean(arr2)

3.6666666666666665

In [139]:
np.std(arr2)

2.3570226039551585

In [140]:
np.var(arr2)

5.555555555555556

In [141]:
np.min(arr2)

1

In [142]:
np.max(arr2)

8

In [143]:
np.argmin(arr2)

0

In [144]:
np.argmax(arr2)

7

In [145]:
arr2

array([[1, 2, 2],
       [4, 5, 2],
       [7, 8, 2]])

In [146]:
lst01 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lst02 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr01 = np.array(lst01)
arr02 = np.array(lst02)
np.dot(arr01, arr02)


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [147]:
N = 1_000_000

In [148]:
%timeit np.random.standard_normal(N)

20.5 ms ± 895 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [149]:
np.random

<module 'numpy.random' from 'C:\\Users\\alimo\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\random\\__init__.py'>

In [150]:
[normalvariate(0, 1) for _ in range(5)]

[-0.05944657518503268,
 0.114748929567109,
 0.5985666094311243,
 -0.21333902312535194,
 0.5903981747543167]

In [151]:
np.random.standard_normal((2,2))

array([[-2.10812285, -0.3626948 ],
       [ 0.11692031,  1.431365  ]])

In [165]:
import random as randm

In [169]:
rand_sample = [randm.normalvariate(0,1) for i in range(5)]
rand_sample_arr = np.array(rand_sample)

In [170]:
np.percentile(rand_sample_arr, 90)

0.223465369702033

In [172]:
hist_values, bin_edges = np.histogram(rand_sample_arr, bins=10)
hist_values

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 2], dtype=int64)

In [173]:
bin_edges

array([-0.80890173, -0.70470457, -0.60050741, -0.49631025, -0.39211309,
       -0.28791593, -0.18371877, -0.07952161,  0.02467555,  0.12887271,
        0.23306987])

In [179]:
random_arr = np.random.rand(3,3)
random_arr

array([[0.07298794, 0.70396017, 0.7322989 ],
       [0.35588168, 0.54959372, 0.47699997],
       [0.75997634, 0.19854916, 0.78518258]])

In [181]:
shuffled = np.random.permutation(random_arr)
shuffled

array([[0.07298794, 0.70396017, 0.7322989 ],
       [0.75997634, 0.19854916, 0.78518258],
       [0.35588168, 0.54959372, 0.47699997]])